src/components/HelloWorld.vue
src/components/UserQuestionMenue.vue
src/styles/color-properties.css

Componente erstellt
- neue custom-properties
- konnte die checkbox nicht in der liste einbinden

feat: add qustion componente

---

src/router/index.js
src/views/StefansView.vue
vite.config.js

Bug fix resolves #18 
<p>
Bug war ein Typo im importieren und ein fehlerhafter pfad aufruf (/components/ hat gefehlt.
Zudem fehlt der @ alias für (./src) den wir von Vue CLI kennen.
Habe den in die vite.config.js hinzugefügt.
[Add Import Alias from Vue CLI in Vite](https://vueschool.io/articles/vuejs-tutorials/import-aliases-in-vite/)
</p>
</details>

fix: stefans view is visible and adds @ alias for path finding

---

src/App.vue
src/components/input-elements/InputText.vue
src/router/index.js
src/views/DanielsView.vue

Aufgaben vom Issue umgesetzt und nachfolgende Ideen notiert.
Resolves #27

feat: adds input Component and example DanielsView

---

src/App.vue
src/router/index.js
src/styles/color-properties.css
src/views/LogView.vue

23 create log in page

---

src/App.vue
src/components/input-elements/InputText.vue
src/views/LogView.vue

Includes password show/hide toggle option in InputeText.vue component. Resolves #40

40 create passwort toggle

---

src/App.vue
src/router/index.js
src/styles/color-properties.css
src/views/LogView.vue
src/views/MainPageView.vue

feat: add mainpageview-mobile and desktop

---

src/components/input-elements/Button.vue
src/views/StefansView.vue

- Button Componente erstellt - button.vue
- clean up - style btn
- liegt derzeit in Stefans View
- original im Login in View belassen

feat: add button componente

---

src/components/Calender.vue

Geprüft auf merge Konflikte. Kann gemerged werden.

chore: implements changing of current date

---

src/components/FilterDropDown.vue
src/components/UserQuestionMenue.vue

Ich habe das Dropdown Menu sowohl im Filter DropDown als auch im User Question Menu der Aufgabe entsprechend angepasst.

100 filterdropdownmenue modifizieren

---

src/styles/color-properties.css
src/styles/global.css

- neue Cp´s in Platzhalter Klassen eingesetzt
- Cp´´s mit Größenangaben wie rem,px aus dem color-properties entfernt und in global css eingebunden

feat: set new Custom properties

---

src/components/input-elements/BackButton.vue
src/components/input-elements/Button.vue
src/views/LogView.vue

- fix bug
-create componente für Back Button
-buton componenen alle eingebdunen
- alte buttons entfernt

chore: fix bug in login card- add backbuttopn componente

---

src/views/LogView.vue

chore: clear code Z: 379-382

---

src/components/input-elements/Button.vue
src/styles/color-properties.css

feat: add disabled class to button.vue

---

src/components/input-elements/CheckBox.vue
src/styles/color-properties.css

- dark mdoe hinzugefügt
- - 2 neue CP´s
- clean up code

feat: dark mode checkbox compöonente

---

src/components/main-component/AccordionDefault.vue
src/styles/color-properties.css
src/views/StefansView.vue

feta: add accordion comöonente

---

src/components/main-component/NavBar.vue
src/components/user-menue/FaqMenue.vue
src/styles/color-properties.css
src/views/StefansView.vue

feat:add faq componente

---

src/assets/Car-Types/Bus.svg
src/assets/Car-Types/Combi.svg
src/assets/Car-Types/Limousine.svg
src/components/Calendar.vue
src/components/icon-type/IconType.vue
src/components/input-elements/Button.vue
src/components/main-component/CarOwnerAccordion.vue
src/components/messenger/CustomerReviews.vue
src/views/UserProfileView.vue

- Limousine und Kombi Icon gesetzt
- in Icon ype Componente integriert

167 add icons combi and limousine

---

src/components/user-menue/FaqMenue.vue

HTML-Struktur befüllt erst einmal ohne Kirstens stage-Vorschlag.

feat FAQ für Owner wurde eingefügt

---

src/components/input-elements/Button.vue
src/styles/color-properties.css
src/views/LogView.vue

- CP´s für BTN und Log In Page erstellt
- farben angepasst
- logo im Login entfernt

feat: add Dm to buttons and LogIn page

---

src/components/main-component/expand-site-cards/FaqClientExpandCard.vue
src/components/main-component/expand-site-cards/FaqOwnerExpandCard.vue

Zwei Dinge konnte ich nicht fixen: 
UserExpandCards wird nicht angezeigt
Einzelne Fragen sind in Checkbox-Format. Ich vermute, das hängt damit zusammen, dass ich alle Fragen  mit "section class="faq-list__wrapper">"  umschließen muss wie beim ursprünglichen FAQ?

feat.  FAQ Owner / User in Expand cards hinzugefügt

---

src/components/main-component/MainMenue.vue
src/components/main-component/expand-menu-components/CarDataTable.vue
src/components/main-component/expand-menu-components/UserDatesTable.vue
src/components/main-component/expand-site-cards/CarDataExpandCard.vue
src/components/main-component/expand-site-cards/UserDataExpandCard.vue
src/styles/color-properties.css

216 add car profile main menu

---

src/components/main-component/MainMenue.vue
src/components/main-component/NavMenue.vue
src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
src/components/main-component/expand-menu-components/UserDatesTable.vue
src/components/main-component/expand-site-cards/CarDataExpandCard.vue
src/components/main-component/expand-site-cards/DataSafetyExpandCard.vue
src/components/main-component/expand-site-cards/DeleteExpandCard.vue
src/components/main-component/expand-site-cards/FaqClientExpandCard.vue
src/components/main-component/expand-site-cards/FaqOwnerExpandCard.vue
src/components/main-component/expand-site-cards/ImpressumExpandCard.vue
src/components/main-component/expand-site-cards/LogoutEpandCard.vue
src/components/main-component/expand-site-cards/MessageSettingsExpandCard.vue
src/components/main-component/expand-site-cards/TeamExpandCard.vue
src/components/main-component/expand-site-cards/UseExpandCard.vue
src/components/main-component/expand-site-cards/UserDataExpandCard.vue
src/styles/color-properties.css
src/views/MainPageView.vue

-Card für beide varianten
-clean up
-korrekturen von Properties

feat: add delete und logout link + scren

---

src/components/main-component/FooterImpressum.vue
src/styles/color-properties.css
src/views/LogView.vue

220 impressum in login bereich

---

src/components/UserQuestionMenue.vue
src/components/input-elements/CheckBox.vue
src/components/input-elements/InputText.vue
src/components/input-elements/RadioButton.vue
src/components/input-elements/SelectDropDown.vue
src/components/main-component/ExpandMenueFrame.vue
src/components/main-component/MainMenue.vue
src/components/main-component/NavBar.vue
src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
src/components/main-component/expand-menu-components/QuestionMenuExpand.vue
src/components/main-component/expand-site-cards/CarDataExpandCard.vue
src/components/main-component/expand-site-cards/DataSafetyExpandCard.vue
src/components/main-component/expand-site-cards/FaqClientExpandCard.vue
src/components/main-component/expand-site-cards/FaqOwnerExpandCard.vue
src/components/main-component/expand-site-cards/ImpressumExpandCard.vue
src/components/main-component/expand-site-cards/MessageSettingsExpandCard.vue
src/components/main-component/expand-site-cards/TeamExpandCard.vue
src/components/main-component/expand-site-cards/UseExpandCard.vue
src/components/main-component/expand-site-cards/UserDataExpandCard.vue
src/styles/color-properties.css
src/styles/global.css
src/views/LogView.vue

------------------
-------------------------------

221 add fragebogen in section

---

src/components/FilterDropDown.vue
src/components/UserQuestionMenue.vue

Habe Filter-Funktion nach PLZ eingebaut 
und sämtliche Filterfunktionen noch mal refactored.
Überflüssig( geworden)en Code und Kommentare habe ich entfernt.

214 filter logik in filterdropdown komponente einbauen

---

src/components/input-elements/DropDownTwoColumns.vue
src/components/input-elements/InputText.vue
src/components/input-elements/TextAreaWithoutButton.vue
src/components/main-component/expand-site-cards/BookingExpandCard.vue
src/components/messenger/messenger-placeholder/MessengerWindow.vue
src/styles/global.css

chore: add css

---

src/components/Calendar.vue
src/components/main-component/NavBar.vue
src/components/main-component/expand-site-cards/BookingCalendarExpandCard.vue
src/components/messenger/messenger-placeholder/MessageChatWindow.vue
src/styles/color-properties.css

feat: calendar angepasst, chat gefixt, anpassungg custom properties

---

src/App.vue
src/components/UserQuestionMenue.vue
src/components/main-component/expand-menu-components/QuestionMenuExpand.vue
src/router/index.js
src/views/LogView.vue
src/views/UserQuestionView.vue

Resolves #189 
<p>
</p>
</details>

189 daten nach supabase wenn user owner fragebogen ausgefuellt

---

src/components/FilterDropDown.vue

Habe alle console.log's entfernt, die ich gesehen habe.

removes all console.logs

---

src/views/UserProfileView.vue

Section "RatingBar" aus UserProvileView.vue entfernt.

feat. Entfernen der Autos aus dem Kommentarbereich

---

src/components/messenger/messenger-placeholder/MessageChatWindow.vue

test bug fix - chat window footer

---

src/components/main-component/NavBar.vue
src/styles/color-properties.css

feat:fix bug in header chat

---

src/views/UserProfileView.vue

Resolves #248 
<p>
</p>
</details>

chore: adds back to main page functionality in car-user-profil

---

src/components/main-component/MessageMenu.vue
src/views/LogView.vue
src/views/MainPageView.vue

Resolves #235
<p>
Nach dem Anmelden mit einem user gibt es bei der automatischen weiterleitung zum Main immer wieder eine Fehlermeldung das die Id nicht gefunden wird.
Nach Seiten Aktualisierung ist alles wieder normal.
</p>
</details>

fix: fixs bug of #235

---

src/App.vue
src/components/input-elements/DarkModeButton.vue
src/components/main-component/MainMenue.vue
src/views/LogView.vue

feat: dark mode bt anegapsst

---

src/components/main-component/FooterImpressum.vue
src/components/main-component/MainMenue.vue
src/styles/color-properties.css
src/styles/global.css

chore: unnötige Custom properties gelöhsct

---

src/components/icon-type/DifferentTypes.vue
src/components/input-elements/Button.vue
src/components/input-elements/DarkModeButton.vue
src/components/input-elements/InputText.vue
src/components/main-component/FooterImpressum.vue
src/components/main-component/MainMenue.vue
src/components/main-component/MessageMenu.vue
src/components/main-component/NavBar.vue
src/components/main-component/expand-menu-components/TeamSingle.vue
src/components/messenger/MessageBox.vue
src/components/messenger/messenger-placeholder/MessagePin.vue
src/components/messenger/messenger-placeholder/MessageSingle.vue
src/styles/color-properties.css
src/styles/global.css
src/views/LogView.vue
src/views/MainPageView.vue

fixessiehe
https://github.com/danielkull/capp/issues/278

chore:foxbugs

---

src/components/UserQuestionMenue.vue
src/components/input-elements/InputText.vue
src/components/main-component/expand-menu-components/CarDataTable.vue
src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
src/components/main-component/expand-menu-components/FaqSingleQuestion.vue
src/components/main-component/expand-menu-components/MessageOptionMenue.vue
src/components/messenger/MessageBox.vue
src/components/user-menue/FaqMenue.vue
src/views/LogView.vue

Schreibweise E-Mail angepasst
Tippies gefixt

feat RechtschreibfehlerE-Mail überall einheitlich

---

src/components/UserQuestionMenue.vue
src/components/input-elements/DarkModeButton.vue

keine fehleranzeigen i der console auf verschiedneen seiten gefunden
- im faregbogenn wurden font colors angepasst

keine bugs gefunden

---

src/components/input-elements/InputText.vue
src/components/main-component/FooterImpressum.vue
src/styles/color-properties.css

chore: fix css

---

src/components/main-component/MainMenue.vue
src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
src/components/main-component/expand-menu-components/UserDatesTable.vue
src/components/main-component/expand-site-cards/BookingConfirmationExpandCard.vue
src/components/main-component/expand-site-cards/BookingExpandCard.vue
src/components/main-component/expand-site-cards/LogoutExpandCard.vue
src/stores/useGlobalStateStore.js
src/views/MainPageView.vue
src/views/UserProfileView.vue

Resolves #237 
<p>
- Im Moment kann man jegliches Datum Auswählen,  ohne Zeit Abstand und auch das End Datum vorher legen
</p>
</details>

237 datum logik beim buchungsanfrage muss erstellt werden

---

src/components/main-component/FooterImpressum.vue
src/components/main-component/MainMenue.vue
src/components/main-component/expand-menu-components/DeleteLogQuestion.vue
src/components/main-component/expand-menu-components/UserDatesTable.vue
src/components/main-component/expand-site-cards/BookingConfirmationExpandCard.vue
src/components/main-component/expand-site-cards/BookingExpandCard.vue
src/components/main-component/expand-site-cards/DataSafetyExpandCard.vue
src/components/main-component/expand-site-cards/ImpressumExpandCard.vue
src/components/main-component/expand-site-cards/LogoutExpandCard.vue
src/stores/useGlobalStateStore.js
src/views/MainPageView.vue
src/views/UserProfileView.vue

resolves #300 
Bzgl. Referenzen habe ich jetzt nichts gemacht, da ich gerade nicht wusste wohin ich die url leiten soll.

300 logview bug im impressum link

---

src/views/LogView.vue

Fix bug in sign in. Password Validation should now work

fix: password validation now works in sign in

---

src/components/FilterDropDown.vue
src/components/main-component/SmallCarCard.vue

fix cssbugs
